//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaGetAllView
    {
        public int IdMateria { get; set; }
        public string NombreMateria { get; set; }
        public Nullable<decimal> Creditos { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Fecha { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IdSemestre { get; set; }
    }
}
